exclude_paths:
  - tmp
  - vendor

detectors:
  DataClump:
    exclude:
      - TRMNL::API::Requester
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - TRMNL::API::Requester#call
